# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection


#spring.main.web-environment: false
spring.data.rest:
  base-path: /api
  max-page-size: 5000
  default-page-size: 100

spring.jackson.serialization.write_dates_as_timestamps: false

wamp:
  dhusId: Scihub
  dhusUser: test
  dhusPassword: test
  dhusUrl: https://scihub.copernicus.eu/apihub
  pollInterval: 18m
  filter:
  extra:
  connectionTimeout: 200000
  readTimeout: 200000
  autoStart: false
  reindex: false
  upsert: true
  odaInbox: C:/Users/fernando marino/Desktop/report-dhus-oda

server:
  port: 8698
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/csv

spring:
  datasource:
    url: jdbc:h2:file:C:/Users/fernando marino/Desktop/report-dhus-oda/statistics
  jpa:
    hibernate:
      ddl-auto: create





