# ===============================
# = DATA SOURCE
# ===============================
# Set here configurations for the database connection

spring.data.elasticsearch:
  cluster-nodes: 127.0.0.1:9300
#  properties:
#    xpack.security.user: elastic:password

#spring.main.web-environment: false
spring.data.rest:
  base-path: /api
  max-page-size: 5000
  default-page-size: 100

spring.jackson.serialization.write_dates_as_timestamps: false

wamp:
  dhusId: Scihub
  dhusUser: test
  dhusPassword: test
  dhusUrl: https://scihub.copernicus.eu/apihub
  pollInterval: 18m
  filter:
  extra:
  connectionTimeout: 200000
  readTimeout: 200000
  autoStart: false

elasticsearch:
  url: localhost
  port: 9200
  scheme: http
  user: elastic
  password: password

server:
  port: 8698



